### ISSUE TITLE
can it do work for xocde12?

### ISSUE THREAD

**Issue by G5t4r** [brendonjkding/Logos-Xcode11#1]

**Comment by brendonjkding** [comment]
~~Only tested on 12.2 beta, not sure if work on higher version.~~

**Comment by brendonjkding** [comment]
<img width="970" alt="截屏2021-05-17 上午10 57 06" src="https://user-images.githubusercontent.com/47965860/118427038-ebdcda00-b6fe-11eb-8d48-0810335ba845.png">
I can confirm it works.

**Comment by G5t4r** [comment]
Thank you for your reply！
