### ISSUE TITLE
Xcode13 may not supproted?

### ISSUE THREAD

**Issue by Zeke0n** [brendonjkding/Logos-Xcode11#2]
installed on xcode 13 looks like not working.

**Comment by brendonjkding** [comment]
<img width="1072" alt="图片" src="https://user-images.githubusercontent.com/47965860/137776118-7d7aae2a-b7a7-46e4-90cf-6e00c05cac9e.png">


looks like working

**Comment by brendonjkding** [comment]
<img width="602" alt="image" src="https://github.com/user-attachments/assets/fe56d7db-7b94-44c7-b254-253068956102">

closing since looks like even working on Xcode 15
